// <auto-generated />
using System;
using Blazor_Training.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor_Training.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260304070333_FinalPayrollIntegration")]
    partial class FinalPayrollIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor_Training.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDisability")
                        .HasColumnType("bit");

                    b.Property<decimal>("HouseAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsMarried")
                        .HasColumnType("bit");

                    b.Property<string>("KraPin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NhifNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NssfNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("hourlyPay")
                        .HasColumnType("float");

                    b.Property<int>("hoursWorked")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Blazor_Training.Domain.Payslip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasicSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GrossPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HouseAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HousingLevyAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetPay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayeAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PayrollRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PersonalRelief")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShaAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxablePay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TransportAllowance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Payslips");
                });

            modelBuilder.Entity("Blazor_Training.Domain.StatutoryConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("HousingLevy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfLowerLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfLowerRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NssfUpperLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PayeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PersonalRelief")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ShaRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("StatutoryConfigs");
                });
#pragma warning restore 612, 618
        }
    }
}
